# Copyright The Platform Mesh Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if and .gatewayApi.enabled (ne .deploymentTechnology "argocd") .gatewayApi.kustomization }}
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: {{ .gatewayApi.name }}
  namespace: {{ .helmReleaseNamespace }}
  labels:
    core.platform-mesh.io/operator-created: "true"
spec:
{{- if .kubeConfigEnabled }}
  kubeConfig:
    secretRef:
      name: {{ .kubeConfigSecretName }}
      key: {{ .kubeConfigSecretKey }}
{{- end }}
  force: false
  interval: {{ .gatewayApi.kustomization.interval }}
  path: {{ .gatewayApi.kustomization.path }}
  prune: true
  sourceRef:
    kind: GitRepository
    name: {{ .gatewayApi.name }}
{{- end }}
