# Copyright The Platform Mesh Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: tenancy.kcp.io/v1alpha1
kind: WorkspaceAuthenticationConfiguration
metadata:
  name: orgs-authentication
spec:
  jwt:
    - issuer:
        url: https://{{ .baseDomainPort }}/keycloak/realms/welcome
        audiences:
        {{- if .welcomeAudiences }}
        {{- range .welcomeAudiences }}
        - {{ . }}
        {{- end }}
        {{- else }} []
        {{- end }}
        audienceMatchPolicy: MatchAny
        {{- with .domainCADec }}
        certificateAuthority: |
{{ . | indent 10 }}
        {{- end }}
      claimMappings:
        groups:
          claim: groups
          prefix: ""
        username:
      {{- if eq .featureDisableEmailVerification "true" }}
          expression: claims.{{ .userClaim }}
      {{- else }}
          claim: {{ .userClaim }}
          prefix: ""
      {{- end }}
      {{- if eq .featureDisableEmailVerification "true" }}
      claimValidationRules:
        - expression: "claims.?email_verified.orValue(true) == true || claims.?email_verified.orValue(true) == false"
          message: "Allowing both verified and unverified emails"
      {{- end }}
