# Copyright The Platform Mesh Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: ui.platform-mesh.io/v1alpha1
kind: ContentConfiguration
metadata:
  labels:
    ui.platform-mesh.io/entity: main
  name: main-os-accounts
spec:
  inlineConfiguration:
    content: |-
      {
          "name": "os-accounts",
          "creationTimestamp": "2022-05-17T11:37:17Z",
          "luigiConfigFragment": {
              "data": {
                  "nodes": [
                      {
                          "visibleForFeatureToggles": ["os-provider"],
                          "pathSegment": "os-accounts",
                          "navigationContext": "accounts",
                          "label": "OS Accounts",
                          "icon": "product",
                          "order": 301,
                          "entityType": "main",
                          "loadingIndicator": {
                              "enabled": false
                          },
                          "keepSelectedForChildren": true,
                          "url": "/assets/platform-mesh-portal-ui-wc.js#generic-os-list-view",
                          "webcomponent": {
                              "selfRegistered": true,
                              "type": "module"
                          },
                          "context": {
                              "resourceDefinition": {
                                  "apiGroup": "core_platform_mesh_io",
                                  "entityCollection": "Accounts",
                                  "entity": "Account",
                                  "scope": "Cluster",
                                  "version": "v1alpha1",
                                  "ui": {
                                      "logoUrl": "https://platform-mesh.io/main/pm_logo.svg",
                                      "listView": {
                                          "fields": [
                                              {
                                                  "label": "Name",
                                                  "property": "metadata.name"
                                              },
                                              {
                                                  "label": "Namespace",
                                                  "property": "metadata.namespace"
                                              },
                                              {
                                                  "label": "Description",
                                                  "property": "spec.description"
                                              }
                                          ],
                                          "filters": [
                                             { "label": "All" },
                                             { "label": "My projects", "value": "{context.userId}", "property": "metadata.name", "default": "true" },
                                             { "label": "Default namespace", "value": "default", "property": "metadata.namespace" }
                                          ]
                                      }
                                  }
                              }
                          },
                          "children": [
                              {
                                  "pathSegment": ":core_platform-mesh_io_accountId",
                                  "hideFromNav": true,
                                  "keepSelectedForChildren": false,
                                  "defineEntity": {
                                      "id": "core_platform-mesh_io_account",
                                      "type": "account",
                                      "contextKey": "core_platform-mesh_io_accountId",
                                      "dynamicFetchId": "core_platform-mesh_io_account",
                                      "additionalContextKeys": ["accountPath"]
                                  },
                                  "context": {
                                      "accountId": ":core_platform-mesh_io_accountId",
                                      "core_platform-mesh_io_accountId": ":core_platform-mesh_io_accountId",
                                      "resourceId": ":core_platform-mesh_io_accountId"
                                  },
                                  "navHeader": {
                                    "label": ":core_platform-mesh_io_accountId"
                                  }
                              }
                          ]
                      }
                  ]
              }
          }
      }
    contentType: json
