# Copyright The Platform Mesh Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .gatewayApi.enabled }}
apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  labels:
    artifact: chart
    {{- if .gatewayApi.kustomization }}
    repo: git
    {{- else }}
    repo: oci
    {{- end }}
  name: {{ .gatewayApi.name }}
  namespace: {{ .releaseNamespace }}
spec:
  componentRef:
    name: {{ .ocm.component.name }}
  ocmConfig:
    - apiVersion: delivery.ocm.software/v1alpha1
      kind: Repository
      name: {{ .ocm.repo.name }}
      namespace: {{ .releaseNamespace }}
  resource:
    byReference:
      referencePath:
      {{- range .ocm.referencePath }}
        - name: {{ .name }}
      {{- end }}
        - name: {{ .gatewayApi.name }}
      resource:
        name: {{ .gatewayApi.ocmResourceName }}
{{- end }}
